database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "senha"
  dbName: "minecraft"
invite:
  maxInvitationTime: 5 # * minutes
  maxAllyInvitationTime: 1 # * dias
redis:
  host: localhost
  port: 6379
  database: 1